FROM python:3.12-bookworm

# 设置工作目录
WORKDIR /app

# 更新软件源
RUN apt update

# 安装基础系统依赖
RUN apt install redis-server -y

#删除apt缓存
RUN rm -rf /var/lib/apt/lists/*

#安装uv
RUN pip install --no-cache-dir uv


ENTRYPOINT ["tail", "-f", "/dev/null"]

